# Generated by Django 5.2.4 on 2025-07-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website_Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_arrival_feature_display', models.BooleanField(default=False)),
                ('contact_email_notification', models.BooleanField(default=False)),
            ],
        ),
    ]
