# Generated by Django 5.2.4 on 2025-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_website_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_setting',
            name='contact_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
