# Generated by Django 5.2.4 on 2025-07-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_office_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='footer_image/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
