# Generated by Django 5.2.4 on 2025-08-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_footer_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer_Image',
        ),
        migrations.DeleteModel(
            name='Office_information',
        ),
    ]
