# Generated by Django 5.2.4 on 2025-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_footer_image_delete_office_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="sl",
            field=models.IntegerField(default=0),
        ),
    ]
