# Generated by Django 5.2.4 on 2025-08-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_category_sl"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
